name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Update repo.
      run: |
        git submodule update --init --recursive
    - name: Build hacPack
      run: |
        cmake -S . -B build
        cmake --build build
    - name: Build hacPack-Tools
      run: make -C hacPack-Tools/hacPackTools-NACP -j
    #- name: make build folder
    #  run: |
    #    mkdir Out/
    #    mkdir Out/hacPackTools-NACP/
    #    mv hacpack* Out/
    #    mv hacPack-Tools/hacPackTools-NACP/hptnacp* Out/hacPackTools-NACP/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: Hacpack
        # Directory containing files to upload
        path: build/hackPack.exe
